name = "groebner"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Groebner"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
# weak.linter.indentation = true
weak.linter.mathlibStandardSet = true
weak.linter.flexible = false
weak.linter.style.header = false

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "«doc-gen4»"
git = "https://github.com/leanprover/doc-gen4"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "Groebner"

[[lean_exe]]
name = "PrintInfo"
srcDir = "scripts"
